source "https://rubygems.org"

gem "activesupport", require: "active_support/all"
gem "sinatra", "~> 1.4.6", require: "sinatra/base"
gem "slim", "~> 3.0.6"
gem "rack_csrf", require: "rack/csrf"
gem "rake"
gem "thin", "~> 1.6.4"

group :development do
  gem "sinatra-reloader", require: "sinatra/reloader"
end
