source "https://rubygems.org"

gem "sinatra", require: "sinatra/base"
gem "slim"
gem "rack_csrf", require: "rack/csrf"
gem "activesupport", require: "active_support/all"
gem "rake"
gem "json"

group :development do
  gem "sinatra-reloader", require: "sinatra/reloader"
end
